### ISSUE TITLE
TypeError in Injection model

### ISSUE THREAD

**Issue by micahwoodard** [AllenNeuralDynamics/aind-data-schema#1065] opened 2024-09-16 17:03 UTC
**Describe the bug**
I'm getting an error when trying to import Session in the latest version of the schema. When running an import line in an environment with only the aind-data-schema pip installed, I'll get a TypeError saying 'list' is not a valid discriminated union variant; should be a 'BaseModel' or 'dataclass' stemming from the Injection model.  When I comment out the [injection_materials](https://github.com/AllenNeuralDynamics/aind-data-schema/blob/ebd9319596402dd8bf2c88e84bed64bd7cee696c/src/aind_data_schema/core/procedures.py#L393C5-L395C61) attribute, I am then able to import with no errors.

**To Reproduce**
`from aind_data_schema.core.session import Session`

**Screenshots**
![image](https://github.com/user-attachments/assets/0eef3f18-3bdf-4e7d-80d2-936c1730cf0c)

**Comment by micahwoodard** [comment] 2024-09-16 17:32
I think this might be a more pervasive issue for the List type. I am also getting this error in Rig class

**Comment by micahwoodard** [comment] 2024-09-16 18:32
running on dev fixes the Injection model but not the errors I'm getting from trying to import aind_data_schema.core.rig

**Comment by bruno-f-cruz** [comment] 2024-09-16 18:42
Weird... Are you sure you are regenerating your environment? Running on dev should pin the pydantic version to <2.9. Try:

```cmd
python -m venv .venv
activate
pip install .["dev"]
``` 
from the root of this repo.

I can successfully run this:

```python
import aind_data_schema.core.rig as rig
import pydantic
print(rig.Rig)  # <class 'aind_data_schema.core.rig.Rig'>
print(pydantic.__version__)  # 2.9.1
```

Additionally, I can manually unpin the pydantic version and run it with either 2.8.x or 2.9.1.

**Comment by bruno-f-cruz** [comment] 2024-09-23 17:10
Latest from pip or latest from GitHub? If you installed latest from pip make sure to additionally pin pydantic<2.9.

**Comment by dbirman** [comment] 2024-09-23 18:48
@micahwoodard I think this is now fixed on the dev branch, including on the latest pydantic 2.9.2, can you confirm whether you have any issues anymore?

**Comment by dbirman** [comment] 2024-09-23 23:11
Closing this for now I can't reproduce the issue with the recent changes on dev, feel free to re-open if the issue persists!

**Closed by dbirman** 2024-09-23 23:11 UTC

**Comment by micahwoodard** [comment] 2024-09-24 15:16
Thank you @dbirman and @bruno-f-cruz for working on this! Sorry I didn't get a chance to check yesterday
