### ISSUE TITLE
move `EphysModule` fields to `EphysSession`

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#249] opened 2023-04-17 17:21 UTC
- arc angle
- module angle
- rotation angle
- transform

also: 
- fix the "data" typo in the transform description
- add a lens to `StickMicroscope`

**Comment by jsiegle** [comment] 2023-04-17 19:48
Rig JSON:
- Switch "port index" description to use one-based indexing
- Remove radius units for disc platform
- Add Neuropixels probe headstage models, and optional serial number field for headstages
- Add "Notes" field to `DomeModule` class

Session JSON:
- For each probe, add manipulator coordinate for brain surface location (Z coordinate only)

**Comment by saskiad** [comment] 2023-04-17 20:48
I'm not sure we should remove the radius units - its important for being able to determine the distance the mouse runs on the disc.

**Comment by saskiad** [comment] 2023-04-17 20:48
I don't think we can make serial numbers optional for some devices and not others. Can you just enter N/A for headstages?

**Comment by jsiegle** [comment] 2023-04-17 21:42
> I'm not sure we should remove the radius units - its important for being able to determine the distance the mouse runs on the disc.

The issue is that the unit is specified both in the `radius` field and in the `radius_unit` field, and it's currently possible for these to conflict: https://github.com/AllenNeuralDynamics/aind-data-schema/blob/2d18f1657f4faf747af26e9da71fdcbc45c35b4f/src/aind_data_schema/device.py#L334-L335

> I don't think we can make serial numbers optional for some devices and not others. Can you just enter N/A for headstages?

This is fine

**Comment by saskiad** [comment] 2023-04-17 21:58
ah, sorry I misread the radius unit comment.  
We need the radius unit. It will show up in json as "radius": 5. Even though the title has a unit in it, that title doesn't show up in the json. This is how the units work throughout the schema. It was a sad day adding those in.

**Comment by saskiad** [comment] 2023-05-02 20:46
closed by PR #277

**Closed by saskiad** 2023-05-02 20:46 UTC
